export { default as Word } from './Word';
export { default as Domain } from './Domain';
export { default as Term } from './Term';
export { default as Approval } from './Approval';
export { default as ApprovalDetail } from './ApprovalDetail';
export { default as WordUpdate } from './WordUpdate';
export { default as WordDetail } from './WordDetail';
export { default as TermDetail } from './TermDetail';
export { default as DomainDetail } from './DomainDetail';